# Previsão de Corridas

Exploração do banco de dados SQLite da Fórmula 1: visão geral do schema, qualidade dos dados e análise.

**Objetivo do projeto:** criar um modelo capaz de prever o *standing* (classificação) da corrida antes mesmo dela começar.

**Conteúdo**
1. Inicialização (imports, configuração, helpers e conexão)
2. Visão geral do schema
3. Qualidade dos dados (relatório de nulos)
4. Limpeza das corridas sprint
5. Exploração de `race_data`

## 1. Inicialização

Um único bloco que prepara tudo para o resto do notebook rodar: imports,
configuração, helpers e conexão com a base de trabalho.

Como funciona a base de dados:

- `DB_ORIGINAL` (`formula.db`): o arquivo baixado, NUNCA é modificado.
- `DB_TRABALHO` (`formula_trabalho.db`): cópia usada em todas as consultas e alterações. Precisa já existir: crie-a uma vez copiando o original.

Helpers disponíveis:

- `connect()`: abre (ou reutiliza) a conexão com a cópia de trabalho, usando `sqlite3.Row` como row factory. Exige que a cópia já exista.
- `query(sql, params)`: executa um SELECT e retorna um `DataFrame` (o helper principal).
- `run(sql, params)`: executa comandos não-SELECT (DDL/DML) e retorna o número de linhas afetadas.
- `row_count(table)`: retorna o número de linhas de uma tabela.
- `box_plot(...)`: box plot de `numcol` agrupado por `catcol`, a partir de SQL ou de um DataFrame.

In [14]:
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Configuração dos bancos
DB_ORIGINAL = Path("formula.db")
DB_TRABALHO = Path("formula_trabalho.db")

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (8, 6)

# Helpers de consulta
_conn: sqlite3.Connection | None = None


def connect() -> sqlite3.Connection:
    """Abre (ou reutiliza) a conexão com a cópia de trabalho do banco.

    A cópia (DB_TRABALHO) precisa já existir; o original nunca é aberto
    nem modificado.
    """
    global _conn
    if _conn is None:
        if not DB_TRABALHO.exists():
            raise FileNotFoundError(
                f"Cópia de trabalho '{DB_TRABALHO}' não encontrada. "
                f"Crie-a a partir de '{DB_ORIGINAL}' antes de continuar."
            )
        _conn = sqlite3.connect(DB_TRABALHO)
        _conn.row_factory = sqlite3.Row
        print(f"Banco de dados '{DB_TRABALHO}' aberto com sucesso.")
    return _conn


def query(sql: str, params: tuple = ()) -> pd.DataFrame:
    """Executa um SELECT e retorna o resultado como DataFrame."""
    return pd.read_sql_query(sql, connect(), params=params)


def run(sql: str, params: tuple = ()) -> int:
    """Executa um comando DDL/DML e retorna o número de linhas afetadas."""
    cur = connect().execute(sql, params)
    _conn.commit()
    return cur.rowcount


def row_count(table: str) -> int:
    """Retorna o número de linhas de uma tabela."""
    return query(f"SELECT COUNT(*) AS n FROM {table}")["n"].iloc[0]


# Helpers de visualização
def box_plot(query_or_df, catcol: str, numcol: str, **kwargs):
    """Box plot de numcol agrupado por catcol, a partir de SQL ou de um DataFrame."""
    df = query(query_or_df) if isinstance(query_or_df, str) else query_or_df
    plt.figure(figsize=(8, 6))
    ax = sns.boxplot(x=catcol, y=numcol, data=df, **kwargs)
    plt.tight_layout()
    return ax


# Inicializa a conexão
conn = connect()

Banco de dados 'formula_trabalho.db' aberto com sucesso.

## 2. Visão geral do schema

Helpers para inspecionar tabelas, colunas e contagem de linhas.

In [15]:
def list_tables() -> list[str]:
    """Retorna os nomes de todas as tabelas do banco, em ordem alfabética."""
    rows = connect().execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
    return [row[0] for row in rows]


def columns(table: str) -> pd.DataFrame:
    """Retorna o PRAGMA table_info de uma tabela como DataFrame."""
    return query(f"PRAGMA table_info({table})")


def schema_overview() -> pd.DataFrame:
    """Uma linha por tabela: quantidade de colunas e de linhas."""
    tabelas = list_tables()
    return pd.DataFrame(
        [{"table": t, "columns": len(columns(t)), "rows": row_count(t)} for t in tabelas]
    )

In [16]:
tabelas = list_tables()
print(f"Tabelas disponíveis no banco ({len(tabelas)}):")
for i, nome_tabela in enumerate(tabelas, start=1):
    print(f"{i:2}. {nome_tabela}")

Tabelas disponíveis no banco (31):
 1. chassis
 2. circuit
 3. circuit_layout
 4. constructor
 5. constructor_chronology
 6. continent
 7. country
 8. driver
 9. driver_family_relationship
10. engine
11. engine_manufacturer
12. entrant
13. grand_prix
14. race
15. race_constructor_standing
16. race_data
17. race_driver_standing
18. season
19. season_constructor
20. season_constructor_standing
21. season_driver
22. season_driver_standing
23. season_engine_manufacturer
24. season_entrant
25. season_entrant_chassis
26. season_entrant_constructor
27. season_entrant_driver
28. season_entrant_engine
29. season_entrant_tyre_manufacturer
30. season_tyre_manufacturer
31. tyre_manufacturer

In [17]:
schema_overview()

                               table  columns    rows
0                            chassis        4    1153
1                            circuit       13      78
2                     circuit_layout        5     160
3                        constructor       22     187
4             constructor_chronology        5     217
5                          continent        4       7
6                            country        7     249
7                             driver       32     917
8         driver_family_relationship        4      86
9                             engine        7     424
10               engine_manufacturer       20      78
11                           entrant        2     830
12                        grand_prix        7      54
13                              race       47    1172
14         race_constructor_standing        9   10632
15                         race_data       71  187314
16              race_driver_standing        8   21495
17                            season        1      77
18                season_constructor       19    1079
19       season_constructor_standing        8     721
20                     season_driver       19    3416
21            season_driver_standing        7    1681
22        season_engine_manufacturer       18     560
23                    season_entrant        3    1799
24            season_entrant_chassis        5    2292
25        season_entrant_constructor        4    1925
26             season_entrant_driver        8    3882
27             season_entrant_engine        5    2027
28  season_entrant_tyre_manufacturer        5    1955
29          season_tyre_manufacturer       15     160
30                 tyre_manufacturer       16       9

## 3. Qualidade dos dados (relatório de nulos)

`null_report()` calcula o percentual de nulos de cada coluna de uma tabela.
Sem argumento, gera o relatório do banco inteiro. Entender onde há dados faltantes
é essencial para decidir quais *features* podem alimentar o modelo de previsão.

In [18]:
def null_report(table: str) -> pd.DataFrame:
    """Retorna contagem e percentual de nulos por coluna de uma tabela."""
    total = row_count(table)
    if total == 0:
        return pd.DataFrame(columns=["table", "column", "nulls", "rows", "null_pct"])

    colunas = [row[1] for row in connect().execute(f"PRAGMA table_info({table})")]
    contagens = {
        col: connect().execute(f"SELECT COUNT(*) FROM {table} WHERE {col} IS NULL").fetchone()[0]
        for col in colunas
    }
    return pd.DataFrame(
        [
            {
                "table": table,
                "column": col,
                "nulls": n,
                "rows": total,
                "null_pct": round(100 * n / total, 2),
            }
            for col, n in contagens.items()
        ]
    )


def full_null_report(tables: list[str] | None = None) -> pd.DataFrame:
    """Relatório de nulos de todas as tabelas (ou apenas das informadas)."""
    tabelas = tables or list_tables()
    return pd.concat([null_report(t) for t in tabelas], ignore_index=True)

In [19]:
report = full_null_report()

print("Percentual de nulos por coluna em cada tabela:")
print("-" * 50)
for nome_tabela, grupo in report.groupby("table", sort=False):
    print(f"\nTabela: {nome_tabela}")
    for _, linha in grupo.iterrows():
        print(f"  - {linha.column}: {linha.null_pct:.2f}% nulos ({linha.nulls}/{linha.rows})")

Percentual de nulos por coluna em cada tabela:
--------------------------------------------------

Tabela: chassis
  - id: 0.00% nulos (0/1153)
  - constructor_id: 0.00% nulos (0/1153)
  - name: 0.00% nulos (0/1153)
  - full_name: 0.00% nulos (0/1153)

Tabela: circuit
  - id: 0.00% nulos (0/78)
  - name: 0.00% nulos (0/78)
  - full_name: 0.00% nulos (0/78)
  - previous_names: 79.49% nulos (62/78)
  - type: 0.00% nulos (0/78)
  - direction: 0.00% nulos (0/78)
  - place_name: 0.00% nulos (0/78)
  - country_id: 0.00% nulos (0/78)
  - latitude: 0.00% nulos (0/78)
  - longitude: 0.00% nulos (0/78)
  - length: 0.00% nulos (0/78)
  - turns: 0.00% nulos (0/78)
  - total_races_held: 0.00% nulos (0/78)

Tabela: circuit_layout
  - id: 0.00% nulos (0/160)
  - circuit_id: 0.00% nulos (0/160)
  - effective: 0.00% nulos (0/160)
  - length: 0.00% nulos (0/160)
  - turns: 0.00% nulos (0/160)

Tabela: constructor
  - id: 0.00% nulos (0/187)
  - name: 0.00% nulos (0/187)
  - full_name: 0.00% nulos (0/187)
  - country_id: 0.00% nulos (0/187)
  - best_championship_position: 57.75% nulos (108/187)
  - best_starting_grid_position: 5.88% nulos (11/187)
  - best_race_result: 16.58% nulos (31/187)
  - best_sprint_race_result: 91.98% nulos (172/187)
  - total_championship_wins: 0.00% nulos (0/187)
  - total_race_entries: 0.00% nulos (0/187)
  - total_race_starts: 0.00% nulos (0/187)
  - total_race_wins: 0.00% nulos (0/187)
  - total_1_and_2_finishes: 0.00% nulos (0/187)
  - total_race_laps: 0.00% nulos (0/187)
  - total_podiums: 0.00% nulos (0/187)
  - total_podium_races: 0.00% nulos (0/187)
  - total_points: 0.00% nulos (0/187)
  - total_championship_points: 0.00% nulos (0/187)
  - total_pole_positions: 0.00% nulos (0/187)
  - total_fastest_laps: 0.00% nulos (0/187)
  - total_sprint_race_starts: 0.00% nulos (0/187)
  - total_sprint_race_wins: 0.00% nulos (0/187)

Tabela: constructor_chronology
  - constructor_id: 0.00% nulos (0/217)
  - position_display_order: 0.00% nulos (0/217)
  - other_constructor_id: 0.00% nulos (0/217)
  - year_from: 0.00% nulos (0/217)
  - year_to: 13.36% nulos (29/217)

Tabela: continent
  - id: 0.00% nulos (0/7)
  - code: 0.00% nulos (0/7)
  - name: 0.00% nulos (0/7)
  - demonym: 0.00% nulos (0/7)

Tabela: country
  - id: 0.00% nulos (0/249)
  - alpha2_code: 0.00% nulos (0/249)
  - alpha3_code: 0.00% nulos (0/249)
  - ioc_code: 16.87% nulos (42/249)
  - name: 0.00% nulos (0/249)
  - demonym: 3.61% nulos (9/249)
  - continent_id: 0.00% nulos (0/249)

Tabela: driver
  - id: 0.00% nulos (0/917)
  - name: 0.00% nulos (0/917)
  - first_name: 0.00% nulos (0/917)
  - last_name: 0.00% nulos (0/917)
  - full_name: 0.00% nulos (0/917)
  - abbreviation: 0.00% nulos (0/917)
  - permanent_number: 96.95% nulos (889/917)
  - gender: 0.00% nulos (0/917)
  - date_of_birth: 0.00% nulos (0/917)
  - date_of_death: 44.82% nulos (411/917)
  - place_of_birth: 0.00% nulos (0/917)
  - country_of_birth_country_id: 0.00% nulos (0/917)
  - nationality_country_id: 0.00% nulos (0/917)
  - second_nationality_country_id: 99.24% nulos (910/917)
  - best_championship_position: 57.80% nulos (530/917)
  - best_starting_grid_position: 13.63% nulos (125/917)
  - best_race_result: 25.95% nulos (238/917)
  - best_sprint_race_result: 96.07% nulos (881/917)
  - total_championship_wins: 0.00% nulos (0/917)
  - total_race_entries: 0.00% nulos (0/917)
  - total_race_starts: 0.00% nulos (0/917)
  - total_race_wins: 0.00% nulos (0/917)
  - total_race_laps: 0.00% nulos (0/917)
  - total_podiums: 0.00% nulos (0/917)
  - total_points: 0.00% nulos (0/917)
  - total_championship_points: 0.00% nulos (0/917)
  - total_pole_positions: 0.00% nulos (0/917)
  - total_fastest_laps: 0.00% nulos (0/917)
  - total_sprint_race_starts: 0.00% nulos (0/917)
  - total_sprint_race_wins: 0.00% nulos (0/917)
  - total_driver_of_the_day: 0.00% nulos (0/917)
  - total_grand_slams: 0.00% nulos (0/917)

Tabela: driver_family_relationship
  - driver_id: 0.00% nulos (0/86)
  - position_display_order: 0.00% nulos (0/86)
  - other_driver_id: 0.00% nulos (0/86)
  - type: 0.00% nulos (0/86)

Tabela: engine
  - id: 0.00% nulos (0/424)
  - engine_manufacturer_id: 0.00% nulos (0/424)
  - name: 0.00% nulos (0/424)
  - full_name: 0.00% nulos (0/424)
  - capacity: 0.24% nulos (1/424)
  - configuration: 0.24% nulos (1/424)
  - aspiration: 0.24% nulos (1/424)

Tabela: engine_manufacturer
  - id: 0.00% nulos (0/78)
  - name: 0.00% nulos (0/78)
  - country_id: 0.00% nulos (0/78)
  - best_championship_position: 42.31% nulos (33/78)
  - best_starting_grid_position: 5.13% nulos (4/78)
  - best_race_result: 14.10% nulos (11/78)
  - best_sprint_race_result: 89.74% nulos (70/78)
  - total_championship_wins: 0.00% nulos (0/78)
  - total_race_entries: 0.00% nulos (0/78)
  - total_race_starts: 0.00% nulos (0/78)
  - total_race_wins: 0.00% nulos (0/78)
  - total_race_laps: 0.00% nulos (0/78)
  - total_podiums: 0.00% nulos (0/78)
  - total_podium_races: 0.00% nulos (0/78)
  - total_points: 0.00% nulos (0/78)
  - total_championship_points: 0.00% nulos (0/78)
  - total_pole_positions: 0.00% nulos (0/78)
  - total_fastest_laps: 0.00% nulos (0/78)
  - total_sprint_race_starts: 0.00% nulos (0/78)
  - total_sprint_race_wins: 0.00% nulos (0/78)

Tabela: entrant
  - id: 0.00% nulos (0/830)
  - name: 0.00% nulos (0/830)

Tabela: grand_prix
  - id: 0.00% nulos (0/54)
  - name: 0.00% nulos (0/54)
  - full_name: 0.00% nulos (0/54)
  - short_name: 0.00% nulos (0/54)
  - abbreviation: 0.00% nulos (0/54)
  - country_id: 3.70% nulos (2/54)
  - total_races_held: 0.00% nulos (0/54)

Tabela: race
  - id: 0.00% nulos (0/1172)
  - year: 0.00% nulos (0/1172)
  - round: 0.00% nulos (0/1172)
  - date: 0.00% nulos (0/1172)
  - time: 93.94% nulos (1101/1172)
  - grand_prix_id: 0.00% nulos (0/1172)
  - official_name: 0.00% nulos (0/1172)
  - qualifying_format: 0.00% nulos (0/1172)
  - sprint_qualifying_format: 97.95% nulos (1148/1172)
  - circuit_id: 0.00% nulos (0/1172)
  - circuit_layout_id: 0.00% nulos (0/1172)
  - circuit_type: 0.00% nulos (0/1172)
  - direction: 0.00% nulos (0/1172)
  - course_length: 0.00% nulos (0/1172)
  - turns: 0.00% nulos (0/1172)
  - laps: 0.00% nulos (0/1172)
  - distance: 0.00% nulos (0/1172)
  - scheduled_laps: 92.83% nulos (1088/1172)
  - scheduled_distance: 92.83% nulos (1088/1172)
  - drivers_championship_decider: 0.00% nulos (0/1172)
  - constructors_championship_decider: 0.00% nulos (0/1172)
  - pre_qualifying_date: 100.00% nulos (1172/1172)
  - pre_qualifying_time: 100.00% nulos (1172/1172)
  - free_practice_1_date: 93.94% nulos (1101/1172)
  - free_practice_1_time: 93.94% nulos (1101/1172)
  - free_practice_2_date: 95.48% nulos (1119/1172)
  - free_practice_2_time: 95.48% nulos (1119/1172)
  - free_practice_3_date: 95.48% nulos (1119/1172)
  - free_practice_3_time: 95.48% nulos (1119/1172)
  - free_practice_4_date: 100.00% nulos (1172/1172)
  - free_practice_4_time: 100.00% nulos (1172/1172)
  - qualifying_1_date: 100.00% nulos (1172/1172)
  - qualifying_1_time: 100.00% nulos (1172/1172)
  - qualifying_2_date: 100.00% nulos (1172/1172)
  - qualifying_2_time: 100.00% nulos (1172/1172)
  - qualifying_date: 93.94% nulos (1101/1172)
  - qualifying_time: 93.94% nulos (1101/1172)
  - sprint_qualifying_date: 98.46% nulos (1154/1172)
  - sprint_qualifying_time: 98.46% nulos (1154/1172)
  - sprint_race_date: 98.46% nulos (1154/1172)
  - sprint_race_time: 98.46% nulos (1154/1172)
  - sprint_race_laps: 97.44% nulos (1142/1172)
  - sprint_race_distance: 97.44% nulos (1142/1172)
  - sprint_race_scheduled_laps: 99.66% nulos (1168/1172)
  - sprint_race_scheduled_distance: 99.66% nulos (1168/1172)
  - warming_up_date: 100.00% nulos (1172/1172)
  - warming_up_time: 100.00% nulos (1172/1172)

Tabela: race_constructor_standing
  - race_id: 0.00% nulos (0/10632)
  - position_display_order: 0.00% nulos (0/10632)
  - position_number: 0.16% nulos (17/10632)
  - position_text: 0.00% nulos (0/10632)
  - constructor_id: 0.00% nulos (0/10632)
  - engine_manufacturer_id: 0.00% nulos (0/10632)
  - points: 0.00% nulos (0/10632)
  - positions_gained: 4.28% nulos (455/10632)
  - championship_won: 0.00% nulos (0/10632)

Tabela: race_data
  - race_id: 0.00% nulos (0/187314)
  - type: 0.00% nulos (0/187314)
  - position_display_order: 0.00% nulos (0/187314)
  - position_number: 6.02% nulos (11279/187314)
  - position_text: 0.00% nulos (0/187314)
  - driver_number: 0.00% nulos (0/187314)
  - driver_id: 0.00% nulos (0/187314)
  - constructor_id: 0.00% nulos (0/187314)
  - engine_manufacturer_id: 0.00% nulos (0/187314)
  - tyre_manufacturer_id: 0.00% nulos (0/187314)
  - practice_time: 74.31% nulos (139186/187314)
  - practice_time_millis: 74.31% nulos (139186/187314)
  - practice_gap: 75.47% nulos (141363/187314)
  - practice_gap_millis: 75.47% nulos (141363/187314)
  - practice_interval: 75.47% nulos (141363/187314)
  - practice_interval_millis: 75.47% nulos (141363/187314)
  - practice_laps: 79.07% nulos (148118/187314)
  - qualifying_time: 81.89% nulos (153388/187314)
  - qualifying_time_millis: 81.89% nulos (153388/187314)
  - qualifying_q1: 95.18% nulos (178278/187314)
  - qualifying_q1_millis: 95.18% nulos (178278/187314)
  - qualifying_q2: 96.46% nulos (180678/187314)
  - qualifying_q2_millis: 96.46% nulos (180678/187314)
  - qualifying_q3: 97.75% nulos (183096/187314)
  - qualifying_q3_millis: 97.75% nulos (183096/187314)
  - qualifying_gap: 80.63% nulos (151027/187314)
  - qualifying_gap_millis: 80.63% nulos (151027/187314)
  - qualifying_interval: 80.63% nulos (151040/187314)
  - qualifying_interval_millis: 80.63% nulos (151040/187314)
  - qualifying_laps: 90.61% nulos (169731/187314)
  - starting_grid_position_qualification_position_number: 85.99% nulos (161070/187314)
  - starting_grid_position_qualification_position_text: 85.92% nulos (160937/187314)
  - starting_grid_position_grid_penalty: 99.69% nulos (186725/187314)
  - starting_grid_position_grid_penalty_positions: 99.72% nulos (186798/187314)
  - starting_grid_position_time: 86.22% nulos (161498/187314)
  - starting_grid_position_time_millis: 86.22% nulos (161498/187314)
  - race_shared_car: 84.96% nulos (159147/187314)
  - race_laps: 86.00% nulos (161083/187314)
  - race_time: 95.37% nulos (178632/187314)
  - race_time_millis: 95.37% nulos (178632/187314)
  - race_time_penalty: 99.84% nulos (187007/187314)
  - race_time_penalty_millis: 99.84% nulos (187007/187314)
  - race_gap: 91.84% nulos (172025/187314)
  - race_gap_millis: 96.00% nulos (179823/187314)
  - race_gap_laps: 95.84% nulos (179516/187314)
  - race_interval: 96.01% nulos (179841/187314)
  - race_interval_millis: 96.01% nulos (179841/187314)
  - race_reason_retired: 94.58% nulos (177168/187314)
  - race_points: 95.32% nulos (178555/187314)
  - race_pole_position: 84.96% nulos (159147/187314)
  - race_qualification_position_number: 85.35% nulos (159878/187314)
  - race_qualification_position_text: 85.28% nulos (159737/187314)
  - race_grid_position_number: 86.05% nulos (161186/187314)
  - race_grid_position_text: 85.91% nulos (160923/187314)
  - race_positions_gained: 90.86% nulos (170197/187314)
  - race_pit_stops: 93.02% nulos (174232/187314)
  - race_fastest_lap: 84.97% nulos (159167/187314)
  - race_driver_of_the_day: 97.24% nulos (182137/187314)
  - race_grand_slam: 84.96% nulos (159147/187314)
  - fastest_lap_lap: 90.87% nulos (170218/187314)
  - fastest_lap_time: 90.86% nulos (170188/187314)
  - fastest_lap_time_millis: 90.86% nulos (170188/187314)
  - fastest_lap_gap: 91.48% nulos (171350/187314)
  - fastest_lap_gap_millis: 91.48% nulos (171350/187314)
  - fastest_lap_interval: 91.48% nulos (171350/187314)
  - fastest_lap_interval_millis: 91.48% nulos (171350/187314)
  - pit_stop_stop: 87.99% nulos (164824/187314)
  - pit_stop_lap: 87.99% nulos (164824/187314)
  - pit_stop_time: 87.99% nulos (164825/187314)
  - pit_stop_time_millis: 87.99% nulos (164825/187314)
  - driver_of_the_day_percentage: 99.56% nulos (186492/187314)

Tabela: race_driver_standing
  - race_id: 0.00% nulos (0/21495)
  - position_display_order: 0.00% nulos (0/21495)
  - position_number: 0.00% nulos (1/21495)
  - position_text: 0.00% nulos (0/21495)
  - driver_id: 0.00% nulos (0/21495)
  - points: 0.00% nulos (0/21495)
  - positions_gained: 3.26% nulos (700/21495)
  - championship_won: 0.00% nulos (0/21495)

Tabela: season
  - year: 0.00% nulos (0/77)

Tabela: season_constructor
  - year: 0.00% nulos (0/1079)
  - constructor_id: 0.00% nulos (0/1079)
  - position_number: 35.50% nulos (383/1079)
  - position_text: 35.31% nulos (381/1079)
  - best_starting_grid_position: 2.59% nulos (28/1079)
  - best_race_result: 8.71% nulos (94/1079)
  - best_sprint_race_result: 94.35% nulos (1018/1079)
  - total_race_entries: 0.00% nulos (0/1079)
  - total_race_starts: 0.00% nulos (0/1079)
  - total_race_wins: 0.00% nulos (0/1079)
  - total_1_and_2_finishes: 0.00% nulos (0/1079)
  - total_race_laps: 0.00% nulos (0/1079)
  - total_podiums: 0.00% nulos (0/1079)
  - total_podium_races: 0.00% nulos (0/1079)
  - total_points: 0.00% nulos (0/1079)
  - total_pole_positions: 0.00% nulos (0/1079)
  - total_fastest_laps: 0.00% nulos (0/1079)
  - total_sprint_race_starts: 0.00% nulos (0/1079)
  - total_sprint_race_wins: 0.00% nulos (0/1079)

Tabela: season_constructor_standing
  - year: 0.00% nulos (0/721)
  - position_display_order: 0.00% nulos (0/721)
  - position_number: 0.42% nulos (3/721)
  - position_text: 0.00% nulos (0/721)
  - constructor_id: 0.00% nulos (0/721)
  - engine_manufacturer_id: 0.00% nulos (0/721)
  - points: 0.00% nulos (0/721)
  - championship_won: 0.00% nulos (0/721)

Tabela: season_driver
  - year: 0.00% nulos (0/3416)
  - driver_id: 0.00% nulos (0/3416)
  - position_number: 50.82% nulos (1736/3416)
  - position_text: 50.79% nulos (1735/3416)
  - best_starting_grid_position: 10.30% nulos (352/3416)
  - best_race_result: 21.69% nulos (741/3416)
  - best_sprint_race_result: 96.22% nulos (3287/3416)
  - total_race_entries: 0.00% nulos (0/3416)
  - total_race_starts: 0.00% nulos (0/3416)
  - total_race_wins: 0.00% nulos (0/3416)
  - total_race_laps: 0.00% nulos (0/3416)
  - total_podiums: 0.00% nulos (0/3416)
  - total_points: 0.00% nulos (0/3416)
  - total_pole_positions: 0.00% nulos (0/3416)
  - total_fastest_laps: 0.00% nulos (0/3416)
  - total_sprint_race_starts: 0.00% nulos (0/3416)
  - total_sprint_race_wins: 0.00% nulos (0/3416)
  - total_driver_of_the_day: 0.00% nulos (0/3416)
  - total_grand_slams: 0.00% nulos (0/3416)

Tabela: season_driver_standing
  - year: 0.00% nulos (0/1681)
  - position_display_order: 0.00% nulos (0/1681)
  - position_number: 0.06% nulos (1/1681)
  - position_text: 0.00% nulos (0/1681)
  - driver_id: 0.00% nulos (0/1681)
  - points: 0.00% nulos (0/1681)
  - championship_won: 0.00% nulos (0/1681)

Tabela: season_engine_manufacturer
  - year: 0.00% nulos (0/560)
  - engine_manufacturer_id: 0.00% nulos (0/560)
  - position_number: 31.25% nulos (175/560)
  - position_text: 31.07% nulos (174/560)
  - best_starting_grid_position: 1.61% nulos (9/560)
  - best_race_result: 8.39% nulos (47/560)
  - best_sprint_race_result: 95.54% nulos (535/560)
  - total_race_entries: 0.00% nulos (0/560)
  - total_race_starts: 0.00% nulos (0/560)
  - total_race_wins: 0.00% nulos (0/560)
  - total_race_laps: 0.00% nulos (0/560)
  - total_podiums: 0.00% nulos (0/560)
  - total_podium_races: 0.00% nulos (0/560)
  - total_points: 0.00% nulos (0/560)
  - total_pole_positions: 0.00% nulos (0/560)
  - total_fastest_laps: 0.00% nulos (0/560)
  - total_sprint_race_starts: 0.00% nulos (0/560)
  - total_sprint_race_wins: 0.00% nulos (0/560)

Tabela: season_entrant
  - year: 0.00% nulos (0/1799)
  - entrant_id: 0.00% nulos (0/1799)
  - country_id: 0.00% nulos (0/1799)

Tabela: season_entrant_chassis
  - year: 0.00% nulos (0/2292)
  - entrant_id: 0.00% nulos (0/2292)
  - constructor_id: 0.00% nulos (0/2292)
  - engine_manufacturer_id: 0.00% nulos (0/2292)
  - chassis_id: 0.00% nulos (0/2292)

Tabela: season_entrant_constructor
  - year: 0.00% nulos (0/1925)
  - entrant_id: 0.00% nulos (0/1925)
  - constructor_id: 0.00% nulos (0/1925)
  - engine_manufacturer_id: 0.00% nulos (0/1925)

Tabela: season_entrant_driver
  - year: 0.00% nulos (0/3882)
  - entrant_id: 0.00% nulos (0/3882)
  - constructor_id: 0.00% nulos (0/3882)
  - engine_manufacturer_id: 0.00% nulos (0/3882)
  - driver_id: 0.00% nulos (0/3882)
  - rounds: 0.00% nulos (0/3882)
  - rounds_text: 4.30% nulos (167/3882)
  - test_driver: 0.00% nulos (0/3882)

Tabela: season_entrant_engine
  - year: 0.00% nulos (0/2027)
  - entrant_id: 0.00% nulos (0/2027)
  - constructor_id: 0.00% nulos (0/2027)
  - engine_manufacturer_id: 0.00% nulos (0/2027)
  - engine_id: 0.00% nulos (0/2027)

Tabela: season_entrant_tyre_manufacturer
  - year: 0.00% nulos (0/1955)
  - entrant_id: 0.00% nulos (0/1955)
  - constructor_id: 0.00% nulos (0/1955)
  - engine_manufacturer_id: 0.00% nulos (0/1955)
  - tyre_manufacturer_id: 0.00% nulos (0/1955)

Tabela: season_tyre_manufacturer
  - year: 0.00% nulos (0/160)
  - tyre_manufacturer_id: 0.00% nulos (0/160)
  - best_starting_grid_position: 0.00% nulos (0/160)
  - best_race_result: 3.75% nulos (6/160)
  - best_sprint_race_result: 96.25% nulos (154/160)
  - total_race_entries: 0.00% nulos (0/160)
  - total_race_starts: 0.00% nulos (0/160)
  - total_race_wins: 0.00% nulos (0/160)
  - total_race_laps: 0.00% nulos (0/160)
  - total_podiums: 0.00% nulos (0/160)
  - total_podium_races: 0.00% nulos (0/160)
  - total_pole_positions: 0.00% nulos (0/160)
  - total_fastest_laps: 0.00% nulos (0/160)
  - total_sprint_race_starts: 0.00% nulos (0/160)
  - total_sprint_race_wins: 0.00% nulos (0/160)

Tabela: tyre_manufacturer
  - id: 0.00% nulos (0/9)
  - name: 0.00% nulos (0/9)
  - country_id: 0.00% nulos (0/9)
  - best_starting_grid_position: 0.00% nulos (0/9)
  - best_race_result: 0.00% nulos (0/9)
  - best_sprint_race_result: 88.89% nulos (8/9)
  - total_race_entries: 0.00% nulos (0/9)
  - total_race_starts: 0.00% nulos (0/9)
  - total_race_wins: 0.00% nulos (0/9)
  - total_race_laps: 0.00% nulos (0/9)
  - total_podiums: 0.00% nulos (0/9)
  - total_podium_races: 0.00% nulos (0/9)
  - total_pole_positions: 0.00% nulos (0/9)
  - total_fastest_laps: 0.00% nulos (0/9)
  - total_sprint_race_starts: 0.00% nulos (0/9)
  - total_sprint_race_wins: 0.00% nulos (0/9)

In [20]:
# Visão compacta: apenas colunas com nulos, ordenadas por severidade
report[report.null_pct > 0].sort_values("null_pct", ascending=False).head(25)

         table                                         column   nulls    rows  null_pct
163       race                              qualifying_1_date    1172    1172    100.00
178       race                                warming_up_time    1172    1172    100.00
177       race                                warming_up_date    1172    1172    100.00
153       race                            pre_qualifying_date    1172    1172    100.00
154       race                            pre_qualifying_time    1172    1172    100.00
166       race                              qualifying_2_time    1172    1172    100.00
165       race                              qualifying_2_date    1172    1172    100.00
164       race                              qualifying_1_time    1172    1172    100.00
161       race                           free_practice_4_date    1172    1172    100.00
162       race                           free_practice_4_time    1172    1172    100.00
228  race_data                              race_time_penalty  187007  187314     99.84
229  race_data                       race_time_penalty_millis  187007  187314     99.84
221  race_data  starting_grid_position_grid_penalty_positions  186798  187314     99.72
220  race_data            starting_grid_position_grid_penalty  186725  187314     99.69
176       race                 sprint_race_scheduled_distance    1168    1172     99.66
175       race                     sprint_race_scheduled_laps    1168    1172     99.66
258  race_data                   driver_of_the_day_percentage  186492  187314     99.56
73      driver                  second_nationality_country_id     910     917     99.24
170       race                         sprint_qualifying_time    1154    1172     98.46
172       race                               sprint_race_time    1154    1172     98.46
169       race                         sprint_qualifying_date    1154    1172     98.46
171       race                               sprint_race_date    1154    1172     98.46
140       race                       sprint_qualifying_format    1148    1172     97.95
211  race_data                                  qualifying_q3  183096  187314     97.75
212  race_data                           qualifying_q3_millis  183096  187314     97.75

### O caso contra as corridas sprint

Antes de remover as sprints, vamos embasar a decisão nos dados:

- **Formato novo**: a sprint foi introduzida em 2021, então só existe numa fração recente do histórico.
- **Outro ruleset**: a sprint tem pontuação, distância e classificação próprias, ou seja, não é diretamente comparável com a corrida principal que queremos prever.
- **Nulos demais**: no geral, as colunas de sprint ficam vazias para quase todas as corridas do banco, como o relatório acima mostra.

As evidências abaixo consultam o ORIGINAL em modo somente leitura (`mode=ro`, sem risco
de alterá-lo), para que continuem válidas mesmo depois de a limpeza já ter rodado.

In [21]:
# Conexão somente leitura com o original (nunca modifica o arquivo)
original = sqlite3.connect(f"file:{DB_ORIGINAL}?mode=ro", uri=True)
original.row_factory = sqlite3.Row

# As sprints existem só a partir de 2021? (evidência no original)
pd.read_sql_query("""\
    SELECT MIN(year) AS primeiro_ano,
           MAX(year) AS ultimo_ano,
           COUNT(*) AS corridas_com_sprint
    FROM race
    WHERE id IN (
        SELECT DISTINCT race_id FROM race_data WHERE type LIKE 'SPRINT%'
    )
""", original)

   primeiro_ano  ultimo_ano  corridas_com_sprint
0          2021        2026                   29

In [22]:
# Colunas relacionadas a sprint no original: nulos nas tabelas race e race_data
linhas = []
for tabela in ("race", "race_data"):
    total = original.execute(f"SELECT COUNT(*) FROM {tabela}").fetchone()[0]
    for row in original.execute(f"PRAGMA table_info({tabela})"):
        col = row[1]
        if "sprint" not in col.lower():
            continue
        nulos = original.execute(
            f"SELECT COUNT(*) FROM {tabela} WHERE {col} IS NULL"
        ).fetchone()[0]
        linhas.append(
            {
                "table": tabela,
                "column": col,
                "nulls": nulos,
                "rows": total,
                "null_pct": round(100 * nulos / total, 2),
            }
        )

colunas_sprint = pd.DataFrame(linhas).sort_values("null_pct", ascending=False)
original.close()

colunas_sprint

  table                          column  nulls  rows  null_pct
7  race      sprint_race_scheduled_laps   1168  1172     99.66
8  race  sprint_race_scheduled_distance   1168  1172     99.66
4  race                sprint_race_time   1154  1172     98.46
1  race          sprint_qualifying_date   1154  1172     98.46
2  race          sprint_qualifying_time   1154  1172     98.46
3  race                sprint_race_date   1154  1172     98.46
0  race        sprint_qualifying_format   1148  1172     97.95
6  race            sprint_race_distance   1142  1172     97.44
5  race                sprint_race_laps   1142  1172     97.44

## 4. Limpeza das corridas sprint

Com o embasamento acima (formato novo, apenas pós-2021, outro ruleset e nulos demais),
as sprints não ajudam a prever o standing da corrida normal. Removemos então da base de
trabalho tudo que é relacionado a sprint:

- as corridas com sessões sprint em `race_data`;
- também as corridas que têm metadados de sprint preenchidos na própria `race`
  (ex.: corridas futuras do calendário que ainda não têm dados de sessão, como
  o GP de Cingapura 2026);
- os registros de sessão sprint em `race_data`.

In [23]:
# Remove as corridas sprint da tabela race:
# por sessão sprint em race_data OU por metadados de sprint na própria race
deletadas_race = run("""\
    DELETE FROM race
    WHERE id IN (
        SELECT DISTINCT race_id
        FROM race_data
        WHERE type LIKE 'SPRINT%'
    )
    OR COALESCE(
        sprint_qualifying_format,
        sprint_qualifying_date,
        sprint_qualifying_time,
        sprint_race_date,
        sprint_race_time,
        sprint_race_laps,
        sprint_race_distance,
        sprint_race_scheduled_laps,
        sprint_race_scheduled_distance
    ) IS NOT NULL
""")

# Remove os registros de sessão sprint da tabela race_data
deletadas_race_data = run("DELETE FROM race_data WHERE type LIKE 'SPRINT%'")

print(f"Corridas sprint removidas de 'race': {deletadas_race}")
print(f"Registros de sessão sprint removidos de 'race_data': {deletadas_race_data}")
print(f"Corridas restantes: {row_count('race')}")

Corridas sprint removidas de 'race': 30
Registros de sessão sprint removidos de 'race_data': 1645
Corridas restantes: 1142

### Verificação da limpeza

Rodamos o relatório de nulos de novo para confirmar que as sprints realmente saíram. Os registros de sessão sprint em `race_data` devem
ser zero e as colunas de sprint em `race` devem ficar 100% nulas.

In [24]:
# 1) Nenhum registro de sessão sprint deve sobrar em race_data
query("SELECT COUNT(*) AS sprints_restantes_em_race_data FROM race_data WHERE type LIKE 'SPRINT%'")

   sprints_restantes_em_race_data
0                               0

In [25]:
# 2) Null report de novo: colunas de sprint em race agora devem estar 100% nulas
report = full_null_report()

report[
    (report["table"] == "race")
    & report.column.str.contains("sprint", case=False)
][["column", "nulls", "rows", "null_pct"]].sort_values("null_pct", ascending=False)

                             column  nulls  rows  null_pct
140        sprint_qualifying_format   1142  1142     100.0
169          sprint_qualifying_date   1142  1142     100.0
170          sprint_qualifying_time   1142  1142     100.0
171                sprint_race_date   1142  1142     100.0
172                sprint_race_time   1142  1142     100.0
173                sprint_race_laps   1142  1142     100.0
174            sprint_race_distance   1142  1142     100.0
175      sprint_race_scheduled_laps   1142  1142     100.0
176  sprint_race_scheduled_distance   1142  1142     100.0

## 5. Exploração de `race_data`

Nesta seção entendemos as sessões registradas em `race_data`.
Como as corridas sprint foram removidas da base de trabalho, os dados refletem
apenas o fim de semana convencional de corrida, que é o que interessa para a previsão dos standings.

### Tipos de sessão em `race_data`

Contagem de linhas por tipo de sessão.

In [26]:
query("""\
    SELECT type, COUNT(type) AS n
    FROM race_data
    GROUP BY type
    ORDER BY n DESC
""")

                        type      n
0                RACE_RESULT  27577
1          QUALIFYING_RESULT  26998
2     STARTING_GRID_POSITION  25814
3                   PIT_STOP  22490
4                FASTEST_LAP  17126
5     FREE_PRACTICE_1_RESULT  16120
6     FREE_PRACTICE_2_RESULT  15531
7     FREE_PRACTICE_3_RESULT   8845
8        QUALIFYING_1_RESULT   7707
9          WARMING_UP_RESULT   7683
10       QUALIFYING_2_RESULT   7541
11  DRIVER_OF_THE_DAY_RESULT    884
12    FREE_PRACTICE_4_RESULT    706
13     PRE_QUALIFYING_RESULT    647